import { afterEach, test } from 'node:test';
import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { db } from 'sdk';
import { onCallbackQuery, onMessage } from '../tgcloud/lib/bot.js';
import { importData } from '../tgcloud/lib/importer.js';
import { callback, checkErrors, lastText, OWNER, privateMessage, setup, user } from './helpers.mjs';

afterEach(checkErrors);

// Generated by the Python bot's export_payload() (see tests/test_export.py).
const FIXTURE = readFileSync(new URL('./fixtures/finya-export.json', import.meta.url));
const data = () => JSON.parse(FIXTURE.toString('utf-8'));

test('export from the Python bot imports completely', async () => {
  await setup();
  const result = await importData(data(), 'import:test');
  assert.equal(result.done, true);
  assert.equal((await db.get('SELECT COUNT(*) AS c FROM events')).c, 250);
  assert.equal((await db.get('SELECT SUM(points) AS s FROM events')).s, 625);
  assert.deepEqual({ ...(await db.get('SELECT xp, manual_rank FROM profiles WHERE user_id = 102')) }, { xp: 12, manual_rank: 'V' });
  const users = await db.all('SELECT user_id, blocked, subscribed FROM users ORDER BY user_id');
  assert.deepEqual(users.map((u) => [u.user_id, u.blocked, u.subscribed]), [[101, 0, 1], [103, 1, 0], [104, 0, 1]]);
  assert.equal((await db.get("SELECT value FROM settings WHERE key = 'news'")).value, '"Старая новость"');
  assert.equal((await db.get("SELECT value FROM settings WHERE key = 'channel_broadcast_enabled'")).value, 'false');
  assert.equal((await db.get('SELECT status FROM relay_outbox')).status, 'uncertain');
  assert.equal((await db.get('SELECT status FROM blacklist')).status, 'banned');
  assert.equal((await db.get('SELECT COUNT(*) AS c FROM feedback')).c, 1);
  // Importing again changes nothing.
  await importData(data(), 'import:again');
  assert.equal((await db.get('SELECT COUNT(*) AS c FROM events')).c, 250);
  assert.equal((await db.get('SELECT COUNT(*) AS c FROM feedback')).c, 1);
});

test('owner forwards the export file to the bot', async () => {
  const mock = await setup({ getFileContent: async () => new Uint8Array(FIXTURE) });
  const doc = { file_id: 'F1', file_unique_id: 'U1', file_name: 'finya-export-20261009-0100.json' };
  await onMessage(privateMessage(user(5), undefined, { document: doc }));
  assert.equal(mock.called('getFileContent').length, 0);
  await onMessage(privateMessage(OWNER, undefined, { document: doc }));
  assert.match(lastText(mock), /Импорт завершён[\s\S]*сумма XP 332/);
  await onMessage(privateMessage(OWNER, undefined, { document: doc }));
  assert.match(lastText(mock), /уже импортирован/);
  // Imported data is live: the top shows Алиса.
  await onCallbackQuery(callback(user(101), 'xp:top'));
  assert.match(lastText(mock), /1\. Алиса — 320 XP/);
});
