"""Regenerate tgcloud/lib/photo_data.js from ../info.jpg (the runtime has no filesystem)."""
import base64
import textwrap
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
data = base64.b64encode((ROOT / "info.jpg").read_bytes()).decode()
body = "\n".join(f"  '{line}' +" for line in textwrap.wrap(data, 120))[:-2]
out = ROOT / "serverless" / "tgcloud" / "lib" / "photo_data.js"
out.write_text("// info.jpg (start screen) as base64; generated by tools/embed_photo.py.\n"
               f"export const INFO_JPG_BASE64 =\n{body};\n", encoding="utf-8")
print(f"wrote {out} ({len(data)} base64 chars)")
